import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import type { Metadata } from "next";
import './globals.css';

export const metadata: Metadata = {
  title: "Challenge 2024",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Header />
        <div className="bg-[#00102c]">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
